name: img_mask_classifier
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-lightning>=2.0.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - timm>=0.9.0
  - click>=8.0.0
  - tqdm>=4.65.0
  - scikit-learn>=1.2.0
  - joblib>=1.2.0
  - pip>=23.0.0
  - pip:
    - opencv-python>=4.7.0
    - wandb>=0.15.0
